<?php

namespace AppBundle\Repository;

/**
 * TenueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TenueRepository extends \Doctrine\ORM\EntityRepository
{
}
